# config/packages/nelmio_cors.yaml
nelmio_cors:
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['Origin', 'X-Requested-With', 'Content-Type', 'Accept']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
            max_age: 3600
